package Vista;

import Modelo.Modelo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.LinkedList;
import java.lang.Object;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JTextField;
import javax.swing.table.*;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;



public class FormCoordenadasT extends javax.swing.JFrame {

    LinkedList<Modelo> modelos = new LinkedList<>();

    public FormCoordenadasT() {
        initComponents();
        setLocationRelativeTo(null);

        rsscalelabel.RSScaleLabel.setScaleLabel(imagen1, "D:\\UNIVERSIDAD\\CURSO_INTEGRADOR\\PROYECTO_JOEL\\MVC_COORDENADAS\\TransformacionCoordenadasGeoUtm\\src\\Images\\longitud.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(imagen2, "D:\\UNIVERSIDAD\\CURSO_INTEGRADOR\\PROYECTO_JOEL\\MVC_COORDENADAS\\TransformacionCoordenadasGeoUtm\\src\\Images\\latitud.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtGradoLongi = new javax.swing.JTextField();
        txtMinuLongi = new javax.swing.JTextField();
        txtSegLongi = new javax.swing.JTextField();
        txtGradoLati = new javax.swing.JTextField();
        txtMinuLati = new javax.swing.JTextField();
        txtSegLati = new javax.swing.JTextField();
        cbOROC = new javax.swing.JComboBox<>();
        cbNS = new javax.swing.JComboBox<>();
        txtEste = new javax.swing.JTextField();
        txtEste11 = new javax.swing.JTextField();
        cbCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbCalcularArePeri = new javax.swing.JButton();
        txtcoordNorte1 = new javax.swing.JTextField();
        txtPerimetro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAreaha = new javax.swing.JTextField();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        txtcoordEste1 = new javax.swing.JTextField();
        txtcoordcierreEste = new javax.swing.JTextField();
        txtcoordCierreNorte = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtcoordEste2 = new javax.swing.JTextField();
        txtcoordNorte2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtcoordEste3 = new javax.swing.JTextField();
        txtcoordNorte3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtcoordEste4 = new javax.swing.JTextField();
        txtcoordNorte4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtcoordEste5 = new javax.swing.JTextField();
        txtcoordNorte5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtAream2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtAreakm2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtGradoLongi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 48, 28));
        jPanel1.add(txtMinuLongi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 48, 28));
        jPanel1.add(txtSegLongi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 44, 26));
        jPanel1.add(txtGradoLati, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 47, 28));
        jPanel1.add(txtMinuLati, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 50, 28));
        jPanel1.add(txtSegLati, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 45, 28));

        cbOROC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oriente", "Occidente" }));
        jPanel1.add(cbOROC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 80, -1));

        cbNS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sur", "Norte" }));
        jPanel1.add(cbNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 80, -1));
        jPanel1.add(txtEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 398, 148, 30));
        jPanel1.add(txtEste11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 399, 148, 30));

        cbCalcular.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbCalcular.setForeground(new java.awt.Color(255, 0, 0));
        cbCalcular.setText("Transformar");
        cbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cbCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 156, 41));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Grados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Minutos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Segundos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Grados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Minutos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Segunos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Este");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Norte");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Aplicativo de Transformación de Coordenadas Geográficas a UTM");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Ingrese el valor de las Coordendas Geográficas - Latitud ( ° , ' , \")");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Ingrese el valor de las Coordendas Geográficas - Longitud ( ° , ' , \")");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Resultados");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 90, 30));

        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 70, 30));

        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Volver Formulario Principal");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 730, 230, 30));

        jButton1.setText("Cargar Datos CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 160, 30));

        jButton4.setText("Guardar Datos CVS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, 170, 30));

        jButton5.setText("Agregar Resultado a la Tabla");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 200, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 480, 185));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Perimetro");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 654, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Perimetro");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 740, -1, -1));

        cbCalcularArePeri.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbCalcularArePeri.setForeground(new java.awt.Color(255, 153, 0));
        cbCalcularArePeri.setText("Calcular ");
        cbCalcularArePeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCalcularArePeriActionPerformed(evt);
            }
        });
        jPanel1.add(cbCalcularArePeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 120, 30));
        jPanel1.add(txtcoordNorte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 148, 30));
        jPanel1.add(txtPerimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 740, 120, 30));

        jLabel15.setText("1era Coordenadas Transformadas");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, -1));
        jPanel1.add(txtAreaha, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 700, 120, 30));

        imagen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, 140, 130));

        imagen2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 130));
        jPanel1.add(txtcoordEste1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 148, 29));
        jPanel1.add(txtcoordcierreEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 148, 29));
        jPanel1.add(txtcoordCierreNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 148, 29));

        jLabel16.setText("Coordenada de Cierre Poligonal");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Calculo de Area - Perimetro");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, -1, -1));

        jLabel18.setText("2da Coordenadas Transformadas");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, -1, -1));
        jPanel1.add(txtcoordEste2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 148, 29));
        jPanel1.add(txtcoordNorte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 148, 29));

        jLabel19.setText("3era Coordenadas Transformadas");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));
        jPanel1.add(txtcoordEste3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 148, 29));
        jPanel1.add(txtcoordNorte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 148, 29));

        jLabel20.setText("4ta Coordenadas Transformadas");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, -1, -1));
        jPanel1.add(txtcoordEste4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 148, 29));
        jPanel1.add(txtcoordNorte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 148, 29));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("Área (ha)");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 700, -1, -1));

        jLabel22.setText("5ta Coordenadas Transformadas");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));
        jPanel1.add(txtcoordEste5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 148, 29));
        jPanel1.add(txtcoordNorte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, 148, 29));

        jButton7.setText("Export Excel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 120, 30));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setText("Área (m2)");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, -1, -1));
        jPanel1.add(txtAream2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 620, 120, 30));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setText("Área (km2)");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, -1, -1));
        jPanel1.add(txtAreakm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCalcularActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        JTextField caja;
        for (int i = 0; i < jPanel1.getComponentCount(); i++) {
            if (jPanel1.getComponent(i).getClass().getName().equals("javax.swing.JTextField")) {
                caja = (JTextField) jPanel1.getComponent(i);
                caja.setText("");
            }
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // CREACION PARA INSERTAR LOS DATOS AL JTABLE
        Modelo modelodatos = new Modelo();
        modelodatos.setId(modelos.size());
        modelodatos.setCoordenadaEste(Double.parseDouble(txtEste.getText()));
        modelodatos.setCoordenadaNorte(Double.parseDouble(txtEste11.getText()));
        modelos.add(modelodatos);

        //txtEste.setText("");
        //txtNorte.setText("");
        llenarTabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //cargar excel
        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos csv", "csv");

        seleccionarArchivo.setFileFilter(filtro);
        int seleccionar = seleccionarArchivo.showOpenDialog(this);

        if (seleccionar == JFileChooser.APPROVE_OPTION) {
            File archivo = seleccionarArchivo.getSelectedFile();
            CargarArchivo(archivo); //Metodo de cargar Archivo

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //GUARDAR EL ARCHIVO
        

        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos csv", "csv");

        seleccionarArchivo.setFileFilter(filtro);
        int seleccionar = seleccionarArchivo.showOpenDialog(this);

        if (seleccionar == JFileChooser.APPROVE_OPTION) {
            File archivo = seleccionarArchivo.getSelectedFile();
            GuardarArchivo(archivo); //Metodo de Guardar Archivo
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbCalcularArePeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCalcularArePeriActionPerformed
        
        // RECORRER LA TABLA DE JTABLE
        /*
        int fila, columna,nums;
        
        fila = jTable2.getRowCount();
        System.out.println("Fila es"+fila);
        columna = jTable2.getColumnCount();
        System.out.println("Columna es"+columna);
        int[][] arreglo = new int[fila][columna];
        
        ArrayList<Integer> numeros = new ArrayList(); 
        
        for (int i = 0; i < numeros.size(); i++) {
            System.out.println("");
        }
 
   
        //Leer todos la Fila
        
        for (int i = 0; i < arreglo.length; i++) {
            for (int j = 0 ; j < arreglo.length; j++) {
                System.out.printf("Fila "+i+" Columna "+j+"   "+jTable2.getValueAt(i,j)+"\n");
                
            }
         }

        //Leer Columna Coordendasa ESTE
        
          for (int i = 0; i < arreglo.length; i++) {
            for (int j = 1 ; j < arreglo.length-1; j++) {
                System.out.printf("Esteeee    "+jTable2.getValueAt(i,j)+"\n");
            }
          }

         
           //Leer Columna Coordendasa NORTE
        
          for (int i = 0; i < arreglo.length; i++) {
            for (int j = 0 ; j < arreglo.length; j++) {
                System.out.printf("Norteeee    "+jTable2.getValueAt(i,j)+"\n");
            }
          }
          
       

        //Coordendas Este
        for (int i = 0; i < arreglo.length; i++) {
           System.out.println("ESTE   :  "+jTable2.getValueAt(i, 1));
          
        } 
        
     //Coordenadas Norte
        
        for (int i = 1; i <arreglo.length; i++) {
            System.out.println("NORTE  :  "+jTable2.getValueAt(i, 2));
        }
        */
       //SEGUNDO METODO PARA CALCULAR AREA - 
       
        
        double SumatoriaA = ((Double.parseDouble(txtcoordEste1.getText()))*(Double.parseDouble(txtcoordNorte2.getText())))+((Double.parseDouble(txtcoordEste2.getText()))*(Double.parseDouble(txtcoordNorte3.getText())))+ ((Double.parseDouble(txtcoordEste3.getText()))*(Double.parseDouble(txtcoordNorte4.getText())))+((Double.parseDouble(txtcoordEste4.getText()))*(Double.parseDouble(txtcoordNorte5.getText())))+((Double.parseDouble(txtcoordEste5.getText()))*(Double.parseDouble(txtcoordCierreNorte.getText())));
        double SumatoriaB = ((Double.parseDouble(txtcoordNorte1.getText()))*(Double.parseDouble(txtcoordEste2.getText())))+((Double.parseDouble(txtcoordNorte2.getText()))*(Double.parseDouble(txtcoordEste3.getText())))+ ((Double.parseDouble(txtcoordNorte3.getText()))*(Double.parseDouble(txtcoordEste4.getText())))+((Double.parseDouble(txtcoordNorte4.getText()))*(Double.parseDouble(txtcoordEste5.getText())))+((Double.parseDouble(txtcoordNorte5.getText()))*(Double.parseDouble(txtcoordcierreEste.getText())));

        double Aream2 = Math.round((SumatoriaB-SumatoriaA)/2);
        double Areakm2 = (Aream2/1000);
        double Areaha = (Aream2/10000);
        
        
        txtAream2.setText(String.valueOf(Aream2));
        txtAreakm2.setText(String.valueOf(Areakm2));
        txtAreaha.setText(String.valueOf(Areaha));
        
        //punto 1 - punto 2
        double DifencialX12 = ((Double.parseDouble(txtcoordEste2.getText()))-(Double.parseDouble(txtcoordEste1.getText())));
        double DifencialY12 = ((Double.parseDouble(txtcoordNorte2.getText()))-(Double.parseDouble(txtcoordNorte1.getText())));    
        
        //punto 2 - punto 3
        double DifencialX23 = ((Double.parseDouble(txtcoordEste3.getText()))-(Double.parseDouble(txtcoordEste2.getText())));
        double DifencialY23 = ((Double.parseDouble(txtcoordNorte3.getText()))-(Double.parseDouble(txtcoordNorte2.getText())));    
        
        
         //punto 3 - punto 4
        double DifencialX34 = ((Double.parseDouble(txtcoordEste4.getText()))-(Double.parseDouble(txtcoordEste3.getText())));
        double DifencialY34 = ((Double.parseDouble(txtcoordNorte4.getText()))-(Double.parseDouble(txtcoordNorte3.getText())));    
        
         //punto 4 - punto 5
        double DifencialX45 = ((Double.parseDouble(txtcoordEste5.getText()))-(Double.parseDouble(txtcoordEste4.getText())));
        double DifencialY45 = ((Double.parseDouble(txtcoordNorte5.getText()))-(Double.parseDouble(txtcoordNorte4.getText())));    
        
         //punto 5 - punto 1
        double DifencialX51 = ((Double.parseDouble(txtcoordcierreEste.getText()))-(Double.parseDouble(txtcoordEste5.getText())));
        double DifencialY51 = ((Double.parseDouble(txtcoordCierreNorte.getText()))-(Double.parseDouble(txtcoordNorte5.getText())));    
       
       
        double PotenciaDifencialX12 = Math.pow(DifencialX12,2);
        double PotenciaDifencialY12 = Math.pow(DifencialY12,2);
        
        double PotenciaDifencialX23 = Math.pow(DifencialX23,2);
        double PotenciaDifencialY23 = Math.pow(DifencialY23,2);
        
        double PotenciaDifencialX34 = Math.pow(DifencialX34,2);
        double PotenciaDifencialY34 = Math.pow(DifencialY34,2);
        
        double PotenciaDifencialX45 = Math.pow(DifencialX45,2);
        double PotenciaDifencialY45 = Math.pow(DifencialY45,2);
        
        double PotenciaDifencialX51 = Math.pow(DifencialX51,2);
        double PotenciaDifencialY52 = Math.pow(DifencialY51,2);
        
        double SumatoriaX12Y12 = PotenciaDifencialX12 + PotenciaDifencialY12;
        double SumatoriaX23Y23 = PotenciaDifencialX23 + PotenciaDifencialY23;
        double SumatoriaX34Y34 = PotenciaDifencialX34 + PotenciaDifencialY34;
        double SumatoriaX45Y45 = PotenciaDifencialX45 + PotenciaDifencialY45;
        double SumatoriaX52Y52 = PotenciaDifencialX51 + PotenciaDifencialY52;
        
        double raizSumatoriaX12Y12 = Math.sqrt(SumatoriaX12Y12);
        double raizSumatoriaX23Y23 = Math.sqrt(SumatoriaX23Y23);
        double raizSumatoriaX34Y34 = Math.sqrt(SumatoriaX34Y34);
        double raizSumatoriaX45Y45 = Math.sqrt(SumatoriaX45Y45);
        double raizSumatoriaX52Y52 = Math.sqrt(SumatoriaX52Y52);
        
        double Perimetro = Math.round(raizSumatoriaX12Y12+raizSumatoriaX23Y23+raizSumatoriaX34Y34+raizSumatoriaX45Y45+raizSumatoriaX52Y52);
        txtPerimetro.setText(String.valueOf(Perimetro));
 
    }//GEN-LAST:event_cbCalcularArePeriActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       
        int seleccionar = jTable2.rowAtPoint(evt.getPoint());
        
        txtcoordEste1.setText(String.valueOf(jTable2.getValueAt(0,1)));
        txtcoordNorte1.setText(String.valueOf(jTable2.getValueAt(0,2)));
        
        txtcoordEste2.setText(String.valueOf(jTable2.getValueAt(1,1)));
        txtcoordNorte2.setText(String.valueOf(jTable2.getValueAt(1,2)));
        
        txtcoordEste3.setText(String.valueOf(jTable2.getValueAt(2,1)));
        txtcoordNorte3.setText(String.valueOf(jTable2.getValueAt(2,2)));
        
        txtcoordEste4.setText(String.valueOf(jTable2.getValueAt(3,1)));
        txtcoordNorte4.setText(String.valueOf(jTable2.getValueAt(3,2)));
        
        txtcoordEste5.setText(String.valueOf(jTable2.getValueAt(4,1)));
        txtcoordNorte5.setText(String.valueOf(jTable2.getValueAt(4,2)));
        
        txtcoordcierreEste.setText(String.valueOf(jTable2.getValueAt(0,1)));
        txtcoordCierreNorte.setText(String.valueOf(jTable2.getValueAt(0,2)));
     
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        //Exportar a Excel
        try{
            Workbook wb = new XSSFWorkbook();
            Sheet sheet = wb.createSheet("Coordenadas");
            Row rowCol = sheet.createRow(0);
            for (int i = 0; i < jTable2.getColumnCount(); i++) {
                Cell cell = rowCol.createCell(i);
                cell.setCellValue(jTable2.getColumnName(i));
            }
            for (int j = 0; j < jTable2.getRowCount(); j++) {
                Row row = sheet.createRow(j+1);
                for (int k = 0; k < jTable2.getColumnCount(); k++) {
                    Cell cell = row.createCell(k);
                    if(jTable2.getValueAt(j,k) != null){
                        cell.setCellValue(jTable2.getValueAt(j,k).toString());
                    }
                }
            }
        FileOutputStream out = new FileOutputStream(new File("D:\\UNIVERSIDAD\\CURSO_INTEGRADOR\\PROYECTO_JOEL\\MVC_COORDENADAS\\Coordenadas.xlsx"));
        wb.write(out);
        wb.close();
        out.close();
            System.out.println(out);
        }catch(FileNotFoundException e){
            System.out.println(e);
        }catch(IOException io){
            System.out.println(io);
        }
        
        


    }//GEN-LAST:event_jButton7ActionPerformed

    public void GuardarArchivo(File Archivo) {
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            fichero = new FileWriter(Archivo);
            pw = new PrintWriter(fichero);
            //FOREACH
            for (Modelo x : modelos) {
                String linea = x.getId() + "," + x.getCoordenadaEste() + "," + x.getCoordenadaNorte();
                pw.println(linea);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (fichero != null) {
                    fichero.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    //creamos metodo para cargar archivo CVS
    //LECTURA DE LA CARGA DE ARCHIVOS
    public void CargarArchivo(File Archivo) {

        FileReader fr = null;
        BufferedReader br = null;
        try {
            fr = new FileReader(Archivo);
            br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {

                String arreglo[] = linea.split(",");
                if (arreglo.length >= 3) {
                    Modelo md = new Modelo();
                    md.setId(Integer.parseInt(arreglo[0]));
                    md.setCoordenadaEste(Double.parseDouble(arreglo[1]));
                    md.setCoordenadaNorte(Double.parseDouble(arreglo[2]));
                    modelos.add(md);

                }

            }

            llenarTabla();
        } catch (Exception ex) {
            ex.printStackTrace();

        } finally {

            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCoordenadasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCoordenadasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCoordenadasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCoordenadasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCoordenadasT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JButton cbCalcular;
    private javax.swing.JButton cbCalcularArePeri;
    public javax.swing.JComboBox<String> cbNS;
    public javax.swing.JComboBox<String> cbOROC;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    public javax.swing.JTextField txtAreaha;
    public javax.swing.JTextField txtAreakm2;
    public javax.swing.JTextField txtAream2;
    public javax.swing.JTextField txtEste;
    public javax.swing.JTextField txtEste11;
    public javax.swing.JTextField txtGradoLati;
    public javax.swing.JTextField txtGradoLongi;
    public javax.swing.JTextField txtMinuLati;
    public javax.swing.JTextField txtMinuLongi;
    public javax.swing.JTextField txtPerimetro;
    public javax.swing.JTextField txtSegLati;
    public javax.swing.JTextField txtSegLongi;
    public javax.swing.JTextField txtcoordCierreNorte;
    public javax.swing.JTextField txtcoordEste1;
    public javax.swing.JTextField txtcoordEste2;
    public javax.swing.JTextField txtcoordEste3;
    public javax.swing.JTextField txtcoordEste4;
    public javax.swing.JTextField txtcoordEste5;
    public javax.swing.JTextField txtcoordNorte1;
    public javax.swing.JTextField txtcoordNorte2;
    public javax.swing.JTextField txtcoordNorte3;
    public javax.swing.JTextField txtcoordNorte4;
    public javax.swing.JTextField txtcoordNorte5;
    public javax.swing.JTextField txtcoordcierreEste;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla() {

        DefaultTableModel mD = new DefaultTableModel(new String[]{"ID", "CoordenadaEste", "CoordenadaNorte"}, modelos.size());
        jTable2.setModel(mD);

        TableModel tm = jTable2.getModel();

        try {
            for (int i = 0; i < modelos.size(); i++) {

                Modelo m = modelos.get(i);
                tm.setValueAt(m.getId(), i, 0);
                tm.setValueAt(m.getCoordenadaEste(), i, 1);
                tm.setValueAt(m.getCoordenadaNorte(), i, 2);

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
}
